### ISSUE TITLE
Cutoff iVar

### ISSUE THREAD

**Issue by sofstam** [Clinical-Genomics/MUTANT#170]
**What needs to be done:**
Got two requests from Jan Albert and Robert Dyrdak:
 - [ ] Change the cutoff from 0.25 to 0.05
 - [ ] Add the file that is under `ncovIllumina_sequenceAnalysis_callVariants` folder to the deliverables

**Suggestions on how to get it done:**
 - [ ] The line in this [file](https://github.com/Clinical-Genomics/MUTANT/blob/main/mutant/config/hasta/default_config.json#L100) can be changed to 0.05
 - [ ] Add file to deliverable similar to nextclade

**Task is considered finished when:**
- [ ] Cutoff has been changed
- [ ] variant file has been added to deliverables

**Comment by talnor** [comment]
https://github.com/Clinical-Genomics/MUTANT/pull/171
