### ISSUE TITLE
Use GMS-Artic images through dockerhub instead of building locally

### ISSUE THREAD

**Issue by sylvinite** [Clinical-Genomics/MUTANT#85]
**What needs to be done:**
Images built under https://github.com/genomic-medicine-sweden/gms-artic/blob/master/scripts/build_singularity_containers.sh should have a fallback to pull them from dockerhub

- [x] Docker build (MAC) instructions
- [x] Set up solution to push images to Dockerhub (clinicalgenomics)
- [x] Set up solution to pull images from dockerhub

**Suggestions on how to get it done:**
Dockerhub, remote build

**What are the arguments for getting it done:**
The reason for running singularity is usually the exact same reason as to why its not possible to build images with the same account

**Task is considered finished when:**
Pipeline runs on a system that doesn't have sudo singularity build permissions.

**Comment by sylvinite** [comment]
nextflow automatically pulls images from Dockerhub if we set process.container = "dockerhub-user/image-name" for singularity.

**Comment by talnor** [comment]
Done. We can set this up better for GMS Dockerhub later.
