### ISSUE TITLE
FOHM delivery checklist

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/MUTANT#94]
**What needs to be done:**

**MUTANT**
 - [x] Individual consensus fasta files with 01_SE100_SID123 formatted headers in deliverables
 - [x] ncovIllumina_Genotyping_typeVariants/vcf/ content files included in deliverables
 - [x] FOHM komplettering file only contains QC passed samples (TBD: maybe also seq metadata)
 - [x] FOHM pangolin file (new one) containing only sample names and only QC pass samples

**Hermes**
- [x] Support new files

**CG**
- [x] Upload GISAID of only the QC pass samples in komplettering file
- [x] cg upload fohm using sftp
